"""Explicit classification of every MCP tool this server registers.

The single source of truth for what a tool *is*, used to derive MCP
annotations, the computed `read_only` profile, and (Phase C) which calls
the write queue intercepts. Never infer a tool's kind from its name at
runtime: names mislead (`search_execute_query` is a read,
`user_list_create_rule_based_user_list` and `ad_create_responsive_search_ad`
are writes). `tests/test_tool_surface.py` fails when a registered tool has
no entry here, or an entry names a tool that no longer exists.

Kinds:
- ``read``: only reads (Google Ads or our own stores).
- ``ads_write``: can send a mutate RPC to Google Ads.
- ``internal_write``: writes only to our own stores (fixes-log Sheet,
  pending-change queue). `pending_change_apply_pending_change` is here: it
  executes a change that was already queued and reviewed, and the queue
  layer, not this registry, governs it.
- ``local_only``: only meaningful for a local single-operator process.

``destructive`` marks tools that can remove, revoke, retract, end or
overwrite something (MCP ``destructiveHint``).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Literal

ToolKind = Literal["read", "ads_write", "internal_write", "local_only"]


@dataclass(frozen=True)
class ToolMeta:
    kind: ToolKind
    destructive: bool = False


R = ToolMeta("read")
W = ToolMeta("ads_write")
WD = ToolMeta("ads_write", destructive=True)
I = ToolMeta("internal_write")  # noqa: E741
ID = ToolMeta("internal_write", destructive=True)
L = ToolMeta("local_only")
LD = ToolMeta("local_only", destructive=True)

TOOL_REGISTRY: Dict[str, ToolMeta] = {
    "access_invite_create_customer_user_access_invitation": W,
    "access_invite_list_customer_user_access_invitations": R,
    "access_invite_remove_customer_user_access_invitation": WD,
    "account_budget_proposal_create_account_budget_proposal": W,
    "account_budget_proposal_list_account_budget_proposals": R,
    "account_budget_proposal_remove_account_budget_proposal": WD,
    "account_budget_proposal_update_account_budget_proposal": W,
    "account_link_create_account_link": W,
    "account_link_list_account_links": R,
    "account_link_remove_account_link": WD,
    "account_link_update_account_link": W,
    "account_registry_add_account": L,
    "account_registry_list_accounts": L,
    "account_registry_remove_account": LD,
    "ad_create_expanded_text_ad": W,
    "ad_create_responsive_search_ad": W,
    "ad_group_ad_create_ad_group_ad": W,
    "ad_group_ad_label_create_ad_group_ad_label": W,
    "ad_group_ad_label_list_ad_group_ad_labels": R,
    "ad_group_ad_label_remove_ad_group_ad_label": WD,
    "ad_group_ad_list_ad_group_ads": R,
    "ad_group_ad_remove_ad_group_ad": WD,
    "ad_group_ad_update_ad_group_ad_status": W,
    "ad_group_asset_link_asset_to_ad_group": W,
    "ad_group_asset_link_multiple_assets_to_ad_group": W,
    "ad_group_asset_list_ad_group_assets": R,
    "ad_group_asset_remove_asset_from_ad_group": WD,
    "ad_group_asset_set_create_ad_group_asset_set": W,
    "ad_group_asset_set_list_ad_group_asset_sets": R,
    "ad_group_asset_set_remove_ad_group_asset_set": WD,
    "ad_group_asset_update_ad_group_asset_status": W,
    "ad_group_create_ad_group": W,
    "ad_group_criterion_add_audience_criteria": W,
    "ad_group_criterion_add_demographic_criteria": W,
    "ad_group_criterion_add_keywords": W,
    "ad_group_criterion_label_assign_label_to_criterion": W,
    "ad_group_criterion_label_assign_label_to_multiple_criteria": W,
    "ad_group_criterion_label_assign_multiple_labels_to_criterion": W,
    "ad_group_criterion_label_mutate_ad_group_criterion_labels": WD,
    "ad_group_criterion_label_remove_label_from_criterion": WD,
    "ad_group_criterion_remove_ad_group_criterion": WD,
    "ad_group_criterion_update_criterion_bid": W,
    "ad_group_customizer_create_ad_group_customizer": W,
    "ad_group_customizer_create_number_customizer": W,
    "ad_group_customizer_create_price_customizer": W,
    "ad_group_customizer_create_text_customizer": W,
    "ad_group_customizer_mutate_ad_group_customizers": WD,
    "ad_group_customizer_remove_ad_group_customizer": WD,
    "ad_group_label_apply_label_to_ad_group": W,
    "ad_group_label_apply_labels_to_ad_groups": W,
    "ad_group_label_list_ad_group_labels": R,
    "ad_group_label_remove_label_from_ad_group": WD,
    "ad_group_update_ad_group": W,
    "ad_parameter_mutate_ad_parameters": WD,
    "ad_resource_get_ad": R,
    "ad_resource_update_ad_urls": W,
    "ad_update_ad_status": W,
    "ag_bid_mod_create_ad_group_device_bid_modifier": W,
    "ag_bid_mod_create_ad_group_hotel_check_in_day_bid_modifier": W,
    "ag_bid_mod_create_ad_group_hotel_date_selection_bid_modifier": W,
    "ag_bid_mod_list_ad_group_bid_modifiers": R,
    "ag_bid_mod_remove_ad_group_bid_modifier": WD,
    "ag_bid_mod_update_ad_group_bid_modifier": W,
    "ag_crit_custom_mutate_ad_group_criterion_customizers": WD,
    "asset_create_app_asset": W,
    "asset_create_business_message_asset": W,
    "asset_create_call_asset": W,
    "asset_create_call_to_action_asset": W,
    "asset_create_callout_asset": W,
    "asset_create_image_asset": W,
    "asset_create_lead_form_asset": W,
    "asset_create_location_asset": W,
    "asset_create_price_asset": W,
    "asset_create_promotion_asset": W,
    "asset_create_sitelink_asset": W,
    "asset_create_structured_snippet_asset": W,
    "asset_create_text_asset": W,
    "asset_create_youtube_video_asset": W,
    "asset_group_asset_create_asset_group_asset": W,
    "asset_group_asset_remove_asset_group_asset": WD,
    "asset_group_asset_update_asset_group_asset_status": W,
    "asset_group_create_asset_group": W,
    "asset_group_list_asset_groups": R,
    "asset_group_remove_asset_group": WD,
    "asset_group_signal_create_audience_signal": W,
    "asset_group_signal_create_search_theme_signal": W,
    "asset_group_signal_mutate_asset_group_signals": WD,
    "asset_group_signal_remove_asset_group_signal": WD,
    "asset_group_update_asset_group": W,
    "asset_search_assets": R,
    "asset_set_asset_add_asset_to_asset_set": W,
    "asset_set_asset_remove_asset_from_asset_set": WD,
    "asset_set_create_asset_set": W,
    "asset_set_list_asset_sets": R,
    "asset_set_remove_asset_set": WD,
    "asset_set_update_asset_set": W,
    "audience_create_combined_audience": W,
    "audience_insights_generate_audience_composition_insights": R,
    "audience_insights_generate_insights_finder_report": R,
    "audience_insights_generate_suggested_targeting_insights": R,
    "audience_list_audiences": R,
    "audience_remove_audience": WD,
    "audience_update_audience": W,
    "automatically_created_asset_removal_remove_campaign_automatically_created_asset": WD,
    "batch_job_add_operations_to_batch_job": W,
    "batch_job_create_batch_job": W,
    "batch_job_get_batch_job": R,
    "batch_job_list_batch_job_results": R,
    "batch_job_list_batch_jobs": R,
    "batch_job_run_batch_job": W,
    "bid_exclusion_create_bidding_data_exclusion": W,
    "bid_exclusion_list_bidding_data_exclusions": R,
    "bid_exclusion_remove_bidding_data_exclusion": WD,
    "bid_exclusion_update_bidding_data_exclusion": W,
    "bid_seasonal_create_bidding_seasonality_adjustment": W,
    "bid_seasonal_list_bidding_seasonality_adjustments": R,
    "bid_seasonal_remove_bidding_seasonality_adjustment": WD,
    "bid_seasonal_update_bidding_seasonality_adjustment": W,
    "bidding_strategy_create_maximize_conversion_value_strategy": W,
    "bidding_strategy_create_maximize_conversions_strategy": W,
    "bidding_strategy_create_target_cpa_strategy": W,
    "bidding_strategy_create_target_impression_share_strategy": W,
    "bidding_strategy_create_target_roas_strategy": W,
    "billing_setup_create_billing_setup": W,
    "billing_setup_get_billing_setup": R,
    "billing_setup_list_billing_setups": R,
    "billing_setup_list_payments_accounts": R,
    "brand_suggestion_suggest_brands": R,
    "budget_create_campaign_budget": W,
    "budget_update_campaign_budget": W,
    "campaign_asset_link_asset_to_campaign": W,
    "campaign_asset_link_multiple_assets_to_campaign": W,
    "campaign_asset_list_campaign_assets": R,
    "campaign_asset_remove_asset_from_campaign": WD,
    "campaign_asset_set_link_asset_set_to_campaign": W,
    "campaign_asset_set_link_asset_set_to_multiple_campaigns": W,
    "campaign_asset_set_link_multiple_asset_sets_to_campaign": W,
    "campaign_asset_set_mutate_campaign_asset_sets": WD,
    "campaign_asset_set_unlink_asset_set_from_campaign": WD,
    "campaign_bid_modifier_create_interaction_type_bid_modifier": W,
    "campaign_bid_modifier_list_campaign_bid_modifiers": R,
    "campaign_bid_modifier_remove_bid_modifier": WD,
    "campaign_bid_modifier_update_bid_modifier": W,
    "campaign_conversion_goal_update_campaign_conversion_goal": W,
    "campaign_create_campaign": W,
    "campaign_criterion_add_device_criteria": W,
    "campaign_criterion_add_language_criteria": W,
    "campaign_criterion_add_location_criteria": W,
    "campaign_criterion_add_negative_keyword_criteria": W,
    "campaign_criterion_remove_campaign_criterion": WD,
    "campaign_customizer_create_campaign_customizer": W,
    "campaign_customizer_remove_campaign_customizer": WD,
    "campaign_draft_create_campaign_draft": W,
    "campaign_draft_list_campaign_draft_async_errors": R,
    "campaign_draft_list_campaign_drafts": R,
    "campaign_draft_promote_campaign_draft": WD,
    "campaign_draft_remove_campaign_draft": WD,
    "campaign_draft_update_campaign_draft": W,
    "campaign_goal_config_link_campaign_to_goal": W,
    "campaign_goal_config_unlink_campaign_from_goal": WD,
    "campaign_goal_config_update_campaign_goal_config": W,
    "campaign_group_create_campaign_group": W,
    "campaign_group_remove_campaign_group": WD,
    "campaign_group_update_campaign_group": W,
    "campaign_label_apply_label_to_campaign": W,
    "campaign_label_apply_labels_to_campaigns": W,
    "campaign_label_list_campaign_labels": R,
    "campaign_label_remove_label_from_campaign": WD,
    "campaign_shared_set_attach_shared_set_to_campaign": W,
    "campaign_shared_set_attach_shared_sets_to_campaigns": W,
    "campaign_shared_set_detach_shared_set_from_campaign": WD,
    "campaign_shared_set_get_campaigns_using_shared_set": R,
    "campaign_shared_set_list_campaign_shared_sets": R,
    "campaign_shared_set_update_campaign_shared_set_status": W,
    "campaign_update_campaign": W,
    "check_sdk_client_status": L,
    "conv_goal_config_mutate_conversion_goal_campaign_configs": WD,
    "conv_goal_config_update_conversion_goal_campaign_config": W,
    "conversion_adjustment_upload_create_restatement_adjustment": W,
    "conversion_adjustment_upload_create_retraction_adjustment": WD,
    "conversion_adjustment_upload_upload_conversion_adjustments": WD,
    "conversion_create_conversion_action": W,
    "conversion_custom_variable_create_conversion_custom_variable": W,
    "conversion_custom_variable_update_conversion_custom_variable": W,
    "conversion_update_conversion_action": W,
    "conversion_upload_upload_call_conversions": W,
    "conversion_upload_upload_click_conversions": W,
    "conversion_value_rule_create_basic_conversion_value_rule": W,
    "conversion_value_rule_list_conversion_value_rules": R,
    "conversion_value_rule_remove_conversion_value_rule": WD,
    "conversion_value_rule_set_create_conversion_value_rule_set": W,
    "conversion_value_rule_set_remove_conversion_value_rule_set": WD,
    "conversion_value_rule_set_update_conversion_value_rule_set_status": W,
    "conversion_value_rule_update_basic_conversion_value_rule": W,
    "custom_audience_create_custom_audience": W,
    "custom_audience_get_custom_audience_details": R,
    "custom_audience_list_custom_audiences": R,
    "custom_audience_update_custom_audience": W,
    "custom_conversion_goal_create_custom_conversion_goal": W,
    "custom_conversion_goal_mutate_custom_conversion_goals": WD,
    "custom_conversion_goal_remove_custom_conversion_goal": WD,
    "custom_conversion_goal_update_custom_conversion_goal": W,
    "custom_interest_create_custom_interest": W,
    "custom_interest_get_custom_interest_details": R,
    "custom_interest_list_custom_interests": R,
    "custom_interest_update_custom_interest": W,
    "customer_asset_create_customer_asset": W,
    "customer_asset_mutate_customer_assets": WD,
    "customer_asset_remove_customer_asset": WD,
    "customer_asset_set_link_asset_set_to_customer": W,
    "customer_asset_set_unlink_asset_set_from_customer": WD,
    "customer_asset_update_customer_asset_status": W,
    "customer_client_link_create_customer_client_link": W,
    "customer_client_link_list_customer_client_links": R,
    "customer_client_link_update_customer_client_link": W,
    "customer_conversion_goal_mutate_customer_conversion_goals": WD,
    "customer_create_customer_client": W,
    "customer_customizer_create_customer_customizer": W,
    "customer_customizer_create_number_customizer": W,
    "customer_customizer_create_price_customizer": W,
    "customer_customizer_create_text_customizer": W,
    "customer_customizer_mutate_customer_customizers": WD,
    "customer_customizer_remove_customer_customizer": WD,
    "customer_label_create_customer_label": W,
    "customer_label_remove_customer_label": WD,
    "customer_list_accessible_customers": R,
    "customer_manager_link_accept_manager_invitation": W,
    "customer_manager_link_decline_manager_invitation": WD,
    "customer_manager_link_move_client_to_new_manager": WD,
    "customer_manager_link_terminate_manager_link": WD,
    "customer_negative_criterion_add_content_label_exclusions": W,
    "customer_negative_criterion_add_negative_keywords": W,
    "customer_negative_criterion_add_placement_exclusions": W,
    "customer_negative_criterion_list_negative_criteria": R,
    "customer_negative_criterion_remove_negative_criterion": WD,
    "customer_user_access_list_user_access": R,
    "customer_user_access_revoke_user_access": WD,
    "customer_user_access_update_user_access": W,
    "customizer_attribute_create_customizer_attribute": W,
    "customizer_attribute_list_customizer_attributes": R,
    "customizer_attribute_remove_customizer_attribute": WD,
    "customizer_attribute_update_customizer_attribute": W,
    "data_link_create_basic_data_link": W,
    "data_link_list_data_links": R,
    "experiment_arm_create_experiment_arm": W,
    "experiment_arm_mutate_experiment_arms": WD,
    "experiment_arm_remove_experiment_arm": WD,
    "experiment_arm_update_experiment_arm": W,
    "experiment_create_experiment": W,
    "experiment_end_experiment": WD,
    "experiment_list_experiments": R,
    "experiment_promote_experiment": WD,
    "experiment_schedule_experiment": W,
    "fixes_log_list_fixes": R,
    "fixes_log_log_fix": I,
    "fixes_log_update_fix_conclusion": I,
    "fixes_log_update_fix_review": I,
    "geo_target_search_geo_targets": R,
    "geo_target_suggest_geo_targets_by_address": R,
    "geo_target_suggest_geo_targets_by_location": R,
    "goal_create_goal": W,
    "goal_update_goal": W,
    "google_ads_atomic_mutate": WD,
    "google_ads_field_get_field_metadata": R,
    "google_ads_field_get_resource_fields": R,
    "google_ads_field_search_fields": R,
    "google_ads_field_validate_query_fields": R,
    "google_ads_search_google_ads": R,
    "google_ads_search_google_ads_stream": R,
    "identity_verification_get_identity_verification": R,
    "identity_verification_start_identity_verification": W,
    "invoice_list_invoices": R,
    "keyword_add_keywords": W,
    "keyword_plan_ad_group_create_keyword_plan_ad_group": W,
    "keyword_plan_ad_group_mutate_keyword_plan_ad_groups": WD,
    "keyword_plan_ad_group_remove_keyword_plan_ad_group": WD,
    "keyword_plan_ad_group_update_keyword_plan_ad_group": W,
    "keyword_plan_add_keywords_to_plan": W,
    "keyword_plan_campaign_create_keyword_plan_campaign": W,
    "keyword_plan_campaign_mutate_keyword_plan_campaigns": WD,
    "keyword_plan_campaign_remove_keyword_plan_campaign": WD,
    "keyword_plan_campaign_update_keyword_plan_campaign": W,
    "keyword_plan_create_keyword_plan": W,
    "keyword_plan_create_keyword_plan_campaign": W,
    "keyword_plan_get_keyword_ideas": R,
    "keyword_plan_idea_generate_keyword_ideas_from_keywords": R,
    "keyword_plan_idea_generate_keyword_ideas_from_keywords_and_url": R,
    "keyword_plan_idea_generate_keyword_ideas_from_site": R,
    "keyword_plan_idea_generate_keyword_ideas_from_url": R,
    "keyword_remove_keyword": WD,
    "keyword_theme_constant_suggest_keyword_theme_constants": R,
    "keyword_update_keyword_bid": W,
    "kp_adgroup_kw_create_keyword_plan_ad_group_keyword": W,
    "kp_adgroup_kw_mutate_keyword_plan_ad_group_keywords": WD,
    "kp_adgroup_kw_remove_keyword_plan_ad_group_keyword": WD,
    "kp_adgroup_kw_update_keyword_plan_ad_group_keyword": W,
    "kp_campaign_kw_create_keyword_plan_campaign_keyword": W,
    "kp_campaign_kw_mutate_keyword_plan_campaign_keywords": WD,
    "kp_campaign_kw_remove_keyword_plan_campaign_keyword": WD,
    "kp_campaign_kw_update_keyword_plan_campaign_keyword": W,
    "label_apply_label_to_ad_groups": W,
    "label_apply_label_to_campaigns": W,
    "label_create_label": W,
    "label_list_labels": R,
    "label_update_label": W,
    "offline_user_data_job_add_user_data_operations": W,
    "offline_user_data_job_create_customer_match_job": W,
    "offline_user_data_job_get_offline_user_data_job": R,
    "offline_user_data_job_list_offline_user_data_jobs": R,
    "offline_user_data_job_run_offline_user_data_job": W,
    "payments_account_list_payments_accounts": R,
    "pending_change_apply_pending_change": ID,
    "pending_change_get_pending_change": R,
    "pending_change_list_pending_changes": R,
    "pending_change_propose_add_keywords": I,
    "pending_change_propose_add_negative_keywords_to_shared_set": I,
    "pending_change_propose_create_rule_based_user_list": I,
    "pending_change_propose_remove_shared_criterion": I,
    "pending_change_propose_remove_user_list": I,
    "pending_change_propose_update_campaign_bid_target": I,
    "pending_change_propose_update_campaign_budget": I,
    "pending_change_reject_pending_change": I,
    "product_link_create_data_partner_link": W,
    "product_link_create_google_ads_link": W,
    "product_link_create_merchant_center_link": W,
    "product_link_remove_product_link": WD,
    "reach_plan_generate_basic_reach_forecast": R,
    "reach_plan_list_plannable_locations": R,
    "reach_plan_list_plannable_products": R,
    "recommendation_apply_recommendation": W,
    "recommendation_dismiss_recommendation": W,
    "recommendation_get_recommendations": R,
    "remarketing_action_create_remarketing_action": W,
    "remarketing_action_get_remarketing_action_tags": R,
    "remarketing_action_list_remarketing_actions": R,
    "remarketing_action_update_remarketing_action": W,
    "search_execute_query": R,
    "search_search_ad_groups": R,
    "search_search_campaigns": R,
    "search_search_keywords": R,
    "shareable_preview_generate_shareable_previews": R,
    "shared_criterion_add_keywords_to_shared_set": W,
    "shared_criterion_add_placements_to_shared_set": W,
    "shared_criterion_list_shared_criteria": R,
    "shared_criterion_remove_shared_criterion": WD,
    "shared_set_attach_shared_set_to_campaigns": W,
    "shared_set_create_shared_set": W,
    "shared_set_list_shared_sets": R,
    "shared_set_update_shared_set": W,
    "smart_campaign_setting_get_smart_campaign_status": R,
    "smart_campaign_setting_update_smart_campaign_setting": W,
    "smart_campaign_suggest_ad_content": R,
    "smart_campaign_suggest_budget_options": R,
    "smart_campaign_suggest_keyword_themes": R,
    "user_data_upload_customer_match_data": W,
    "user_data_upload_enhanced_conversions": W,
    "user_data_upload_store_sales_data": W,
    "user_list_create_basic_user_list": W,
    "user_list_create_crm_based_user_list": W,
    "user_list_create_logical_user_list": W,
    "user_list_create_rule_based_user_list": W,
    "user_list_create_similar_user_list": W,
    "user_list_customer_type_add_customer_type_to_user_list": W,
    "user_list_customer_type_remove_customer_type_from_user_list": WD,
    "user_list_remove_user_list": WD,
    "user_list_update_user_list": W,
}
